# Basic
title: LILIAN
subtitle: Window to life
description: Live by your nature
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Wenbao Li
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: LIFE AND WORK
url: "http://lilian.info"

# Comment
comment:
    # disqus: lilian
    # duoshuo: lilian
     uy: 1363062691
     wangyi: LILIAN
    #gitment: lilian
          #id: 581bd96523e3f5c2eff6
          #secret: 6ae18be198d13f2a5d023c71effddddfd48b107a

# Social
social:
    weibo: 2344041987
    github: dearLilian
    #gsite: liliandreamworld
    csdn: lilianforever
    # twitter: 
    mail: liwenbao930116@gmail.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: e572ae9801b3a18891f123796b889f77

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-88738012-1   
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/dearLilian/dearLilian.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /blog/:year/:month/:title.html 

markdown: kramdown


kramdown:
  input:  GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge


# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Archive, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}
    - {title: Comments, description: messages, url: '/messages'}
    - {title: Resources, description: links, url: '/links'}      
    - {title: About, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"