# Basic
title: LILIAN
subtitle: å¿ƒçµä¹‹çª—
description: ä¹¦å†™ç”Ÿæ´»ï¼Œå……å®è‡ªæˆ‘
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: dearLilian
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: æ•°æ®æŒ–æ˜ / æœºå™¨å­¦ä¹ 
url: "http://lilian.info"

# Comment
comment:
    # disqus: lilian
    duoshuo: lilian 

# Social
social:
    weibo: 2344041987
    github: dearLilian
    #gsite: liliandreamworld
    csdn: lilianforever
    # twitter: 
    mail: liwenbao930116@gmail.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: e572ae9801b3a18891f123796b889f77

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-88738012-1   
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/dearLilian/dearLilian.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹

markdown: kramdown

permalink: /blog/:year/:month/:title.html 
kramdown:

  auto_ids: true,

  footnote_nr: 1

  entity_output: as_char

  toc_levels: 1..6

  enable_coderay: false


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: åˆ†ç±», description: tags, url: '/tags'}
    - {title: ç•™è¨€æ¿, description: messages, url: '/messages'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"